### ISSUE TITLE
Absurd incorrect elevation (Mont Blanc 🏔🇫🇷)

### ISSUE THREAD

**Issue by Jeremy38100** [rapomon/srtm-elevation#1]
Hi I discover a bug:

Reproduce
```js
const TileSet = require('srtm-elevation').TileSet;
var tileset = new TileSet('./data/');
tileset.getElevation([45.8326, 6.8651], function(err, elevation) {
    if (err) {
        console.log('getElevation failed: ' + err.message);
    } else {
        console.log(elevation);
    }
});
```
Result : `-32768`
Expected : `4810` (more or less)

version : 1.0.3

**Comment by rapomon** [comment]
According to the [Nasa's documentation](https://dds.cr.usgs.gov/srtm/version2_1/Documentation/SRTM_Topo.pdf), voids are flagged with -32768.

> Byte order is Motorola ("big-endian") standard with the most significant byte first. Since they are
> signed integers elevations can range from -32767 to 32767 meters, encompassing the range of
> elevation to be found on the Earth.
> These data also contain occassional voids from a number of causes such as shadowing, phase
> unwrapping anomalies, or other radar-specific causes. Voids are flagged with the value -32768.

So I can do nothing with that, maybe you should consider 0 or a near value when the value is -32768.
