### ISSUE TITLE
Alternative data providers

### ISSUE THREAD

**Issue by thisancog** [rapomon/srtm-elevation#2]
The SRTMElevationDownloader class accepts a provider option, which could be used to use other data (such as the 1 arcsecond SRTM dataset). This does not work insofar, that the file naming structure for the .hgt packets differs between these datasets and the URL is synthesized with the ".SRTMGL1.hgt.zip" suffix (/src/srtm.js, line 111). It would be nice of the user could choose between different datasets, maybe by replacing the provider option with another that just accepts the name of the dataset, rather than the corresponding URI. That way, the suffix could be stored in an Object that maps the dataset name to the URI and the suffix.

**Comment by rapomon** [comment]
Hi.

I just upload a new version to support different datasets, the provider options support a pattern to compose the url in different ways.

Sorry for the delay.
