### ISSUE TITLE
Can´t load data

### ISSUE THREAD

**Issue by asiermusa** [rapomon/srtm-elevation#3]
Hi,

I have this super basic code snippet but I am not able to do work it.

```
   var tileset = new SyncTileSet('./data/', [57, 11], [58, 12], function(err) {
        if (err) {
            console.log(err);
            return;
        }
       
        console.log('loading data...')

        var elevation = tileset.getElevation([57.7, 11.9]);
        console.log(elevation);
    }, {
        username: process.env.NASA_NAME,
        password: process.env.NASA_PASSWORD
    });
```
Even the console.log is not reached... I don´t know where is the mistake in my code.

How have I to import the library?

```
option 1: const SyncTileSet = require('srtm-elevation').SyncTileSet;
option 2: const SyncTileSet = require('./src').SyncTileSet;
```

Second one does not work in my project.

**Comment by rapomon** [comment]
The username and password is only necessary when using the NASA provider. Remove it because the new default provider does not need it. The NASA provider is down since several weeks.

**Comment by rapomon** [comment]
Your code works well for me, you should use option 1 when using the installed library in your project:
`const SyncTileSet = require('srtm-elevation').SyncTileSet;`
I close the incidence unless you let me know that it does not work for you.
